name: Update content JSON files by pulling from the Diedrick CMS API

on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'staging'
    - name: Use cURL to download JSON
      uses: wei/curl@v1.1.1
      with:
        args: >
           https://s3.us-east-2.wasabisys.com/lmec-public-files/temp/dummy.json -o data/dummy.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated action"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
